const i32 xxx = 123;
var i32 asdf = 123;
var i32 yyy;
var (*i32) arr;
# could improve error reporting:
#var *i32 xxxx;
function (*i32) xyz (const i32 x, const i32 y) {
    var i32 a = 2;
    var (*  * ***ABC) b;
    var (*  * ***u64) c;
    var (**asdf) d;
    var (*u8) txt = "hello world\n";
    var i32 z = x = x + y;
    var i32 zz = (x +( x +hello ));
    
    #check this later again
    #var *i32 z;
    return z;
};
struct ABC {
   var i32 x;
   var i32 y;
};


