struct ABC2 {
   var i32 x;
   var i32 y;
};

var u8 num1 = 5;
var u16 num2 = 1000;
var u32 num3 = 1000000;
var u64 num4 = 1000000000000;
var i32 num5 = -1000;
var u64 num6 = -1;
//var u64 num6_ = num6;

var i8  num001 = 0;
var i16 num002 = 0;
var i32 num003 = 0;
var i64 num004 = 0;
var u64 num005 = 0;

var double num7 = 1010101.1010101;
var float num8 = 1.1;
var float num9 = 1111;
//var u64 num10 = 111.111;

function void func1() {
	num6 = 2;
	num7 = 2.345;
	// TODO: try other combinations !!!
	num1 = 1;
	num2 = 2;
	num3 = 4;
	num4 = -100;
	num5 = 10;
	num6 = -2;
	num8 = 2.3456;
	num9 = 222222;
};

function void func2() {
	num1 = num1 + num1;
	num2 = num2 + num2;
	num3 = num3 + num3;
	num4 = num4 + num4;
	num5 = num5 + num5;
	num6 = num6 + num6;
	num7 = num7 + num7;
	num8 = num8 + num8;
	num9 = num9 + num9;
};

function void func3() {
	num1 = num1 + num1 + num1;
	num2 = num2 + 2;
	num2 = 2 + num2 + 2;
	num3 = num1;

	num001 = -1;
	num005 = num001;
	num6 = num005;
};
function void func4() {};
function void func5() {};
